# Generated by Django 4.2.13 on 2024-05-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declarante',
            fields=[
                ('cpf', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=150)),
                ('nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('profissao', models.CharField(default='', max_length=100)),
                ('contaBancaria', models.CharField(default='', max_length=30)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_nickname', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=150)),
                ('user_email', models.EmailField(default='', max_length=254)),
                ('user_age', models.IntegerField(default=0)),
                ('user_password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=20)),
                ('anoCompra', models.IntegerField(default=0)),
                ('valorCompra', models.CharField(default='', max_length=20)),
                ('anoVenda', models.IntegerField(default=0)),
                ('valorVenda', models.CharField(default='', max_length=20)),
                ('declarante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedade', to='api_rest.declarante')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(default='', max_length=30)),
                ('rua', models.CharField(default='', max_length=100)),
                ('numero', models.IntegerField(default=0)),
                ('bairro', models.CharField(default='', max_length=100)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(default='', max_length=100)),
                ('complemento', models.CharField(default='', max_length=150)),
                ('declarante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='api_rest.declarante')),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=20)),
                ('nome', models.CharField(default='', max_length=150)),
                ('documento', models.CharField(default='', max_length=20)),
                ('nascimento', models.DateField()),
                ('declarante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependente', to='api_rest.declarante')),
            ],
        ),
    ]
