# Generated by Django 4.2.13 on 2024-05-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declarante',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='declarante',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
